In [1]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  matplotlib as mpl
import matplotlib.patches as mpaches
from  sklearn.pipeline  import Pipeline
from  sklearn.neighbors  import KNeighborsClassifier
from  sklearn.linear_model  import  LogisticRegression #逻辑回归
from  sklearn.preprocessing  import StandardScaler,PolynomialFeatures

%matplotlib inline 

In [2]:
path=r"../datas/iris.data"

In [3]:
data=pd.read_csv(path,header=None)
data

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
data[4]=pd.Categorical(data[4]).codes #第四列，类型转化为编号
data

0    1    2    3  4
0    5.1  3.5  1.4  0.2  0
1    4.9  3.0  1.4  0.2  0
2    4.7  3.2  1.3  0.2  0
3    4.6  3.1  1.5  0.2  0
4    5.0  3.6  1.4  0.2  0
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

[150 rows x 5 columns]

In [5]:
x,y=np.split(data.values,(4,),axis=1) #列的维度，进行数据切割

In [7]:
x

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [8]:
y

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [9]:
x=x[:,:2] #选择两个特征
x

array([[ 5.1,  3.5],
       [ 4.9,  3. ],
       [ 4.7,  3.2],
       [ 4.6,  3.1],
       [ 5. ,  3.6],
       [ 5.4,  3.9],
       [ 4.6,  3.4],
       [ 5. ,  3.4],
       [ 4.4,  2.9],
       [ 4.9,  3.1],
       [ 5.4,  3.7],
       [ 4.8,  3.4],
       [ 4.8,  3. ],
       [ 4.3,  3. ],
       [ 5.8,  4. ],
       [ 5.7,  4.4],
       [ 5.4,  3.9],
       [ 5.1,  3.5],
       [ 5.7,  3.8],
       [ 5.1,  3.8],
       [ 5.4,  3.4],
       [ 5.1,  3.7],
       [ 4.6,  3.6],
       [ 5.1,  3.3],
       [ 4.8,  3.4],
       [ 5. ,  3. ],
       [ 5. ,  3.4],
       [ 5.2,  3.5],
       [ 5.2,  3.4],
       [ 4.7,  3.2],
       [ 4.8,  3.1],
       [ 5.4,  3.4],
       [ 5.2,  4.1],
       [ 5.5,  4.2],
       [ 4.9,  3.1],
       [ 5. ,  3.2],
       [ 5.5,  3.5],
       [ 4.9,  3.1],
       [ 4.4,  3. ],
       [ 5.1,  3.4],
       [ 5. ,  3.5],
       [ 4.5,  2.3],
       [ 4.4,  3.2],
       [ 5. ,  3.5],
       [ 5.1,  3.8],
       [ 4.8,  3. ],
       [ 5.1,  3.8],
       [ 4.6,

In [6]:
lr=Pipeline([("sc",StandardScaler()),
             ("poly",PolynomialFeatures(degree=2)),
             ("clf",LogisticRegression())]) #处理数据
lr.fit(x,y.ravel()) #训练数据

Pipeline(memory=None,
         steps=[('sc',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('poly',
                 PolynomialFeatures(degree=2, include_bias=True,
                                    interaction_only=False, order='C')),
                ('clf',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='warn', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='warn', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [7]:
y_new=lr.predict(x)#预测数据

In [8]:
np.mean(y_new==y.ravel()) #精确度为81%

0.98

In [9]:
lr=Pipeline([("sc",StandardScaler()),
             ("poly",PolynomialFeatures(degree=2)),
             ("clf",KNeighborsClassifier())]) #处理数据
lr.fit(x,y.ravel()) #训练数据
y_new=lr.predict(x)#预测数据
np.mean(y_new==y.ravel()) #精确度为82.6%

0.96

In [10]:
lr=Pipeline([("sc",StandardScaler()),
             ("poly",PolynomialFeatures(degree=2)),
             ("clf",LogisticRegression())]) #处理数据
lr.fit(x,y.ravel()) #训练数据
y_new=lr.predict(x)#预测数据
np.mean(y_new==y.ravel()) #精确度为82.6%

0.98

In [11]:
y_new_prob=lr.predict_proba(x) #预测
y_new_prob

array([[9.87150210e-01, 4.92069185e-04, 1.23577206e-02],
       [9.83611269e-01, 3.86352687e-03, 1.25252038e-02],
       [9.88755442e-01, 6.59089253e-04, 1.05854682e-02],
       [9.89905890e-01, 1.89268040e-03, 8.20142984e-03],
       [9.90473832e-01, 2.64494496e-04, 9.26167309e-03],
       [9.92623317e-01, 3.01303170e-03, 4.36365166e-03],
       [9.94109394e-01, 7.83180270e-04, 5.10742539e-03],
       [9.88399075e-01, 9.68018598e-04, 1.06329065e-02],
       [9.89588761e-01, 2.36783571e-03, 8.04340370e-03],
       [9.84464321e-01, 1.46993800e-03, 1.40657412e-02],
       [9.85864508e-01, 5.00945176e-04, 1.36345466e-02],
       [9.91852238e-01, 1.00799911e-03, 7.13976306e-03],
       [9.84493497e-01, 1.40880148e-03, 1.40977014e-02],
       [9.88340606e-01, 1.54399978e-04, 1.15049939e-02],
       [9.73782385e-01, 7.02952722e-05, 2.61473196e-02],
       [9.96939588e-01, 3.87536841e-04, 2.67287534e-03],
       [9.92315220e-01, 6.00829835e-04, 7.08395003e-03],
       [9.89210077e-01, 1.18064